### Get Link by Code
GET http://localhost:3000/pmdev

### Get Links by User
GET http://localhost:3000/api/links/9f422aef-b683-4a75-8da5-a3a658277908

### Create Link
post http://localhost:3000/api/links
Content-Type: application/json

{
  "code": "pmdev",
  "url": "https://soupaulodev.com.br",
  "userId": "9f422aef-b683-4a75-8da5-a3a658277908"
}

### Get Metrics by User
GET http://localhost:3000/api/metrics/9f422aef-b683-4a75-8da5-a3a658277908

### User Signup
post http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "name": "Paulo Marques",
  "email": "pm@pm.com",
  "password": "123456"
}

### User Login
post http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "pm@pm.com",
  "password": "123456"
}


### User Logout
delete http://localhost:3000/api/auth/logout/

### User Update
patch http://localhost:3000/api/users/9f422aef-b683-4a75-8da5-a3a658277908
Content-Type: application/json

{
  "name": "Paulo Marques",
  "email": "pm@pm.com",
  "password": "123456"
}